### ISSUE TITLE
Investigate changes in image pull policy support when using latest docker desktop

### ISSUE THREAD

**Issue by markpollack** [cloudlift/lift#7]
`imagePullPolicy: IfNotPresent` does not seem to work anymore.

**Comment by nierajsingh** [comment]
I investigate why the image for the app was not being created in the Docker Daemon for `local` kubernetes using `jib-maven-plugin`, and the problem was related to the `DeploymentService` Java implementation in `lift` itself. `mvn package` was not being executed when running the `platform-deploy` command, so the docker image never got built. 

Consequently the k8s deployment failed on image pull policy, because the image was not there to begin with.

In the `DeploymentService` java code,  executing `mvn  package` was  disabled by this code:

```
				if (false) {
						if (maveDependencyService.containsDependency("kubernetes-spring-starter", "io.dekorate", null)) {
							System.out.println(ansi().fg(GREEN).a("Detected Dekorate dependency."));
							System.out.println(ansi().fg(GREEN).a("Running Maven build to generate Kubernetes resources."));
							String[] mavenBuildCommand = {"./mvnw", "clean", "package", "-P", platform.getProfile()};
							osService.executeCommand(mavenBuildCommand, true);
							//TODO can the output yml file location be customized?
							File k8syml = new File(IoUtils.getWorkingDirectory().getPath() + "/target/classes/META-INF/dekorate/kubernetes.yml");
							System.out.println(ansi().fg(GREEN).a("Using " + k8syml.getAbsolutePath() + "to deploy app to Kubernetes."));
							return this.kubeCtlDeployService.deploy(platformName, k8syml);
						}
					}
```

This is not a solution, but just for testing purpose, if I "enable" the `mvn package` bit above, simply by moving these two lines:

```
			String[] mavenBuildCommand = {"./mvnw", "clean", "package", "-P", platform.getProfile()};
							osService.executeCommand(mavenBuildCommand, true);
```
out of the if statement above so that it is executed, then the `jib` plugin is executed and consequently the image is built in the local Docker Daemon. Image pull policy now works when deploying to Kubernetes, and the k8s deployment is successful.

Since this is not a problem with the `docker-dekstop` or `imagePullPolicy` during K8s deployment, but rather a bug in the `lift`  Java code, I am closing this.
